// The seeded fixture — ONE of everything, written through DB.* inside the page.
//
// Serialised into the browser by the net (it closes over nothing from Node).
// The sheets need something to edit: a session to open, a food to change, a
// recipe to pour. Every write goes through the same public API the app uses,
// so a slice whose signature changes breaks the fixture loudly — a seed that
// fails is reported as a PROBLEM, never skipped, because a sheet captured over
// an empty fixture is a shallower capture that still reads as green.
//
// Ids are generated by uid() — seeded Math.random plus the frozen clock — and
// the capture MASKS them in first-seen order, so nothing here needs to be a
// stable literal.
'use strict';

function seedFixture() {
  const out = { seeded: [], failed: [] };
  const step = (name, fn) => { try { const r = fn(); out.seeded.push(name); return r; } catch (e) { out.failed.push(name + ': ' + (e && e.message || e)); return null; } };
  const today = todayISO();
  out.today = today;
  out.yesterday = addDaysISO(today, -1);

  const exs = DB.exercises.list();
  out.exerciseId = exs[0] && exs[0].id;
  out.exerciseId2 = exs[1] && exs[1].id;
  out.exerciseId3 = exs[2] && exs[2].id;

  out.sessionId = step('session', () => DB.sessions.add({ exerciseId: out.exerciseId, date: out.yesterday, sets: [{ reps: 8, weight: 40 }, { reps: 8, weight: 42.5 }] }).id);

  const ct = (DB.cardioTypes.allTypes() || [])[0];   // allTypes, not list: list() is unreferenced and about to go
  out.cardioTypeId = ct && ct.id;
  out.cardioId = step('cardio', () => { const r = DB.cardio.add({ type: out.cardioTypeId, date: out.yesterday, duration: 30, calories: 180 }); return r && (r.id || (r.entity && r.entity.id)) || (DB.cardio.list ? DB.cardio.list().slice(-1)[0].id : null); });
  out.cardioPlanId = step('cardioPlan', () => { const r = DB.cardioPlan.add({ type: out.cardioTypeId, days: [0, 2, 4], duration: 30 }); const l = DB.cardioPlan.list(); return (r && r.entity && r.entity.id) || (l[l.length - 1] && l[l.length - 1].id); });

  out.sleepId = step('sleep', () => { const r = DB.sleep.add({ date: today, sleepTime: '23:30', wakeTime: '06:45' }); return r && r.id || (DB.sleep.list().slice(-1)[0] || {}).id; });
  out.foodId = step('food', () => { const r = DB.foods.add({ name: 'Grilled chicken', serving: '100 g', calories: 165, protein: 31, carbs: 0, fat: 3.6 }); return r && r.id || (DB.foods.list().slice(-1)[0] || {}).id; });
  out.supplementId = step('supplement', () => { const r = DB.supplements.add({ name: 'Creatine', dose: '5 g', color: '#ff6a00', times: ['08:00'] }); return r && r.id || (DB.supplements.list().slice(-1)[0] || {}).id; });

  step('recipe', () => DB.recipes.add({ name: 'Rice and chicken', servings: 2, items: [
    { name: 'Rice', qty: '200 غ', calories: 260, protein: 5, carbs: 56, fat: 1 },
    { name: 'Chicken', qty: '150 غ', calories: 248, protein: 46, carbs: 0, fat: 5 },
  ] }));
  out.recipe = (DB.recipes.list() || []).slice(-1)[0] || null;

  step('bundle', () => DB.mealBundles.update(null, { name: 'Breakfast', items: [
    { name: 'Eggs', calories: 140, protein: 12, carbs: 1, fat: 10, servings: 2 },
    { name: 'Toast', calories: 80, protein: 3, carbs: 15, fat: 1, servings: 1 },
  ] }));
  out.bundle = (DB.mealBundles.list() || []).slice(-1)[0] || null;

  // A calorie goal is MANDATORY in this app: renderFood opens the calculator 250ms
  // after the Food page renders when none is set, so a fixture without one is a
  // Food page that keeps opening a sheet of its own over whatever the lane opened.
  step('nutrition', () => DB.nutrition.setTargets({ calories: 2200, protein: 160, carbs: 240, fat: 70 }));
  step('foodLog', () => DB.foodLogs.add(today, { name: 'Oats', calories: 150, protein: 5, carbs: 27, fat: 3, servings: 1 }));
  step('water', () => DB.water.add(today, 500));
  step('bodyweight', () => DB.bodyweight.log(today, 78.4));
  step('shopping', () => DB.shopping.addNames([{ name: 'Rice', amount: '1 kg' }, { name: 'Eggs' }], 'cx_shopping_changed'));
  step('plan', () => DB.plan.setRotation({
    cycle: [{ name: 'Push', exerciseIds: [out.exerciseId, out.exerciseId2] }, { name: 'Pull', exerciseIds: [out.exerciseId3] }],
    trainingDays: [0, 2, 4], anchor: out.yesterday,
  }));
  return out;
}

module.exports = { seedFixture };
